force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Aadhaar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Number__c</fullName>
    <label>Aadhaar Number</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Total_Loyality_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Loyality_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loyality Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <label>Gift</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Gift ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Gift_Image__c.field-meta.xml
<CustomField>
    <fullName>Gift_Image__c</fullName>
    <formula>IMAGE( Gift_Image_Link__c , &quot; &quot; ,150,200)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gift Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Gift_Image_Link__c</fullName>
    <label>Gift Image Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Name__c.field-meta.xml
<CustomField>
    <fullName>Gift_Name__c</fullName>
    <label>Gift Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomerDetails.cls
public with sharing class CustomerDetails {
    
    @AuraEnabled(cacheable=true)
    public static List<Gift__c> getGiftsList() {
        return [SELECT Id, Name, Gift_Name__c,Points__c,Gift_Image__c,Gift_Image_Link__c
                FROM Gift__c WITH SECURITY_ENFORCED ORDER BY Points__c ASC Limit 10000];
    }
    
    @AuraEnabled(cacheable=true)
    public static Customer__c getCustomer(String customerPhone) 
    {
        Customer__c customerInfo = [
            SELECT Name__c, Aadhaar_Number__c, Phone__c, Total_Loyality_Points__c,  LastModifiedDate 
            FROM Customer__c 
            WHERE Phone__c LIKE : '%' + customerPhone + '%' WITH SECURITY_ENFORCED
        ];
        return customerInfo;
    }
    
}