force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <label>Gift</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Gift ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Gift_Name__c.field-meta.xml
<CustomField>
    <fullName>Gift_Name__c</fullName>
    <label>Gift Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Station__c/Station__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/Station_Gifts__c.object-meta.xml
<CustomObject>
    <label>Store Gifts</label>
    <nameField>
        <displayFormat>SG-{000}</displayFormat>
        <label>Store Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipName>Station_Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Quantity_InStock__c.field-meta.xml
<CustomField>
    <fullName>Quantity_InStock__c</fullName>
    <formula>Quantity_Added__c  -  Quantity_Used__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity InStock</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Restock_Level__c.field-meta.xml
<CustomField>
    <fullName>Restock_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Restock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Store Gifts</relationshipLabel>
    <relationshipName>Station_Gifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <label>Station</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GiftRestockNotificationHandler.cls
public with sharing class GiftRestockNotificationHandler
{
    public static void sendNotification(List<Station_Gifts__c> giftList)
    {
        CustomNotificationType restockNotification = [SELECT Id, DeveloperName
                                                     FROM CustomNotificationType 
                                                     WHERE DeveloperName = 'Notification_For_Manager' WITH SECURITY_ENFORCED
                                                     LIMIT 1];

        List<Messaging.CustomNotification> customNotificationsToSend = new List<Messaging.CustomNotification>();
        List<Messaging.SingleEmailMessage> emailNotificationsToSend = new List<Messaging.SingleEmailMessage>();

        set<Id> stationIds = new set<Id>();
        set<Id> giftIds = new set<Id>();
        for (Station_Gifts__c gift : giftList) {
            if(gift.Station__c != null){
                stationIds.add(gift.Station__c);
            }
            if(gift.Gift__c != null){
                giftIds.add(gift.Gift__c);
            }
        }
        
        User loggedInUser = [select id,Email from User where Id =: UserInfo.getUserId()];
        
        map<Id,Station__c> mapStation = new map<Id,Station__c>([SELECT Name from Station__c where Id IN:stationIds  WITH SECURITY_ENFORCED]);
        map<Id,Gift__c> mapGift = new map<Id,Gift__c>([SELECT Gift_Name__c FROM Gift__c WHERE Id IN :giftIds  WITH SECURITY_ENFORCED]);
        
        for (Station_Gifts__c gift : giftList) 
        {
            if (gift.Quantity_InStock__c <= gift.Restock_Level__c) 
            {
                // Query for the related gift's name
                String storeName = mapStation.get(gift.Station__c).Name;
                Gift__c relatedGift = mapGift.get(gift.Gift__c);
                String body = 'Gift ' + relatedGift.Gift_Name__c + ' has fallen to or below the restock level for Station: ' + storeName;

                // Create and send custom notification
                Messaging.CustomNotification customNotification = new Messaging.CustomNotification();
                customNotification.setNotificationTypeId(restockNotification.Id);
                customNotification.setSenderId(Userinfo.getUserId());
                customNotification.setBody(body);
                customNotification.setTitle('Gift Restock Needed');
                customNotification.setTargetId(gift.Id);
                customNotification.send(new Set<String> {gift.CreatedById});
                customNotificationsToSend.add(customNotification);

                // Create and send email notification
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setSubject('Gift Needed To Be Restocked for Station: ' + storeName);
                email.setPlainTextBody(body);
                email.setToAddresses(new List<String>{loggedInUser.Email});
                emailNotificationsToSend.add(email);
            }
        }

        // Send email notifications
        if (!emailNotificationsToSend.isEmpty()) {
            Messaging.sendEmail(emailNotificationsToSend);
        }
    }
}