force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <label>Gift</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Gift ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Gift_Image__c.field-meta.xml
<CustomField>
    <fullName>Gift_Image__c</fullName>
    <formula>IMAGE( Gift_Image_Link__c , &quot; &quot; ,150,200)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gift Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Gift_Image_Link__c</fullName>
    <label>Gift Image Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Name__c.field-meta.xml
<CustomField>
    <fullName>Gift_Name__c</fullName>
    <label>Gift Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FetchObjectRecords.cls
public with sharing class FetchObjectRecords {
   
    //Customer Gifts
    @AuraEnabled(cacheable=true)
    public static List<Gift__c> getCustomerGiftsList() {
        List<Gift__c> gifts= [SELECT Id, Name, Gift_Name__c,Points__c,Gift_Image__c,Gift_Image_Link__c
                FROM Gift__c WITH SECURITY_ENFORCED  Limit 10000];
        return gifts;
    }
   
    //Create Gift Record
    @AuraEnabled
    public static void insertGift(String Name,Integer Points, Integer Qty, String ImageUrl)
    {
           if (Schema.sObjectType.Gift__c.isCreateable()) {
            Gift__c gift=new Gift__c();
            gift.Gift_Name__c=Name;
            gift.Points__c=Points;
            gift.Gift_Image_Link__c=ImageUrl;
            insert gift;
        
        }
    }
}