force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Quantity_Claimed__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Claimed__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity Claimed</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Total_Loyality_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Loyality_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loyality Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <label>Gift</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Gift ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station__c/Station__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/Station_Gifts__c.object-meta.xml
<CustomObject>
    <label>Store Gifts</label>
    <nameField>
        <displayFormat>SG-{000}</displayFormat>
        <label>Store Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipName>Station_Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Quantity_Used__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Store Gifts</relationshipLabel>
    <relationshipName>Station_Gifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClaimHandler.cls
public with sharing class ClaimHandler {
    public static void updateGiftAndPoints(List<Claim__c> newClaims) 
    {
        List<id> claimId = new List<id>();
        list<id> gifts= new list<id>();
        list<id>  station=new list<id>();
        for (Claim__c cm : newClaims)
        {
            claimId.add(cm.Id);
            gifts.add(cm.Gift__c);
            station.add(cm.Station__c);
        }
        List<Customer__c> cusList = new List<Customer__c>();
        List<Claim__c> cmList = [SELECT Id, Customer__r.Id,Quantity_Claimed__c,Station__c, Customer__r.Total_Loyality_Points__c, 
                                 Gift__r.Points__c FROM Claim__c WHERE Id IN :claimId WITH SECURITY_ENFORCED];
        Map<id, Station_Gifts__c> mapName = new Map<id, Station_Gifts__c>();
        List<Station_Gifts__c> giftsToUpdate = new List<Station_Gifts__c>();
        Map<String, Station_Gifts__c> stationGiftsMap = new Map<String, Station_Gifts__c>();
        for (Station_Gifts__c gift : [SELECT Id, Quantity_Used__c, Gift__c, Station__c 
                                      FROM Station_Gifts__c 
                                      WHERE Gift__c IN :gifts AND Station__c IN :station WITH SECURITY_ENFORCED]) {
            stationGiftsMap.put(gift.Gift__c + '-' + gift.Station__c, gift);
        }
               
        for (Claim__c cu : cmList) {
            Decimal GiftPoints = cu.Gift__r.Points__c;
            if (cu.Gift__c != null) 
            {
                system.debug('cu.Gift__c'+cu.Gift__c);
                system.debug('cu.Station__c'+cu.Station__c);
                String key = cu.Gift__c + '-' + cu.Station__c;
                if (Schema.sObjectType.Station_Gifts__c.isUpdateable()) {
                    Station_Gifts__c gift = stationGiftsMap.get(key);
                    gift.Quantity_Used__c += cu.Quantity_Claimed__c;
                    giftsToUpdate.add(gift);
                }
            }
            if(cu.Customer__r.Total_Loyality_Points__c>=GiftPoints)
            {
                if (Schema.sObjectType.Customer__c.isUpdateable()) {
                    Customer__c cus = new Customer__c();
                    cus.Id = cu.Customer__r.Id;
                    GiftPoints=GiftPoints*cu.Quantity_Claimed__c;
                    cus.Total_Loyality_Points__c = cu.Customer__r.Total_Loyality_Points__c - GiftPoints;
                    cusList.add(cus); //Add the customer record to the list for update
                }
             }   
        }
        if (Schema.sObjectType.Station_Gifts__c.isUpdateable()) {
            if (!giftsToUpdate.isEmpty()){
                update giftsToUpdate;//Update Gift Data
            } 
        }  
        if (Schema.sObjectType.Customer__c.isUpdateable()) {
            if (!cusList.isEmpty()){
                update cusList; // Update the customer records
            }
        }
    }
}