force-app/main/default/objects/Assign_Store__c/Assign_Store__c.object-meta.xml
<CustomObject>
    <label>Assign Store</label>
    <nameField>
        <label>Assign Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assign Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Quantity_Claimed__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Claimed__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity Claimed</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <label>Gift</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Gift ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Gift_Name__c.field-meta.xml
<CustomField>
    <fullName>Gift_Name__c</fullName>
    <label>Gift Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sales</label>
    <nameField>
        <displayFormat>SID-{00000}</displayFormat>
        <label>Sales ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Employees__c.field-meta.xml
<CustomField>
    <fullName>Employees__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employees</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Station__c/Station__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/Station_Gifts__c.object-meta.xml
<CustomObject>
    <label>Store Gifts</label>
    <nameField>
        <displayFormat>SG-{000}</displayFormat>
        <label>Store Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipName>Station_Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Store Gifts</relationshipLabel>
    <relationshipName>Station_Gifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <label>Station</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/genericDataTableController.cls
public with sharing class genericDataTableController {
    
    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecords(String objectName,List<String> columns) {
        
        String query;
        List<SObject> records= new List<SObject>();
        if(objectName!=null)
        {     
            if(objectName=='User'){
                records =[Select Id,Name,Phone ,RWD_CX__Station__c,RWD_CX__Aadhar_Number__c,Profile.Name from User Where IsActive = true AND ( Profile.Name='System Administrator' OR Profile.Name= 'Standard User' )];
                //query = 'SELECT ' + String.join(columns, ',') + ' FROM ' + objectName + ' where IsActive='+true+' WITH SECURITY_ENFORCED ORDER BY CreatedDate  DESC ';
            	//query = String.escapeSingleQuotes(query);
            }else{
                query = 'SELECT ' + String.join(columns, ',') + ' FROM ' + objectName + '  WITH SECURITY_ENFORCED ORDER BY CreatedDate  DESC ';
                query = String.escapeSingleQuotes(query);
                records= Database.query(query);
            }
         }
        
        return records;
        
    }
    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecords1( String type,Id cid,string objectapiname) {
        
        String query;
        List<SObject> records= new List<SObject>();
        if(type!='empolyee')
        {  
            if(objectapiname=='RWD_CX__Claim__c'){
                list<Claim__c> Customer = [select Id,Name,Station__r.Name,Customer__r.Name__c,Gift__r.Gift_Name__c,
                                           CreatedDate,Quantity_Claimed__c from Claim__c
                                           WHERE Customer__c =:cid WITH SECURITY_ENFORCED];
                
                records.addAll(Customer); 
            }
            else{
                list<Sales__c> Customer = [select Id,Name,Station__r.Name,Customer__r.Name__c,
                                           Employees__r.Name,CreatedDate,Amount__c from Sales__c
                                           WHERE Customer__c =:cid WITH SECURITY_ENFORCED];
                
                records.addAll(Customer); 
                
            }
        }
        else
        {   
            list<Sales__c> Customer = [select Id,Name,Station__r.Name,Customer__r.Name__c,Employees__r.Name,
                                       CreatedDate,Amount__c from Sales__c
                                       WHERE Employees__c =:cid WITH SECURITY_ENFORCED];
            records.addAll(Customer);          
        }          
        return records;
        
    }
    
    @AuraEnabled
    public static List<Sales__c> searchDate(DATE dateStr1, DATE dateStr2){
        
        List<Sales__c> salesObj = [SELECT Id, Name, Customer__c, Employees__c,  Amount__c, Station__c,
                                   CreatedDate FROM Sales__c WHERE CreatedDate >= :dateStr1 AND CreatedDate <= :dateStr2 WITH SECURITY_ENFORCED];
        
        RETURN salesObj;
    }
    
    @AuraEnabled
    public static void deleteSelectedRecords(List<Id> idList) {
        String objectApiName ='' ; 
        Boolean isDeletablecheck = false;
        if (idList == null || idList.isEmpty()) {
            return;
        }
        
        for (Id recordId : idList) {
            if (objectApiName == null || objectApiName == '') {
                objectApiName = recordId.getSObjectType().getDescribe().getName();
            }
            break;
        }
        if(objectApiName == 'RWD_CX__Sales__c'){
            List<Sales__c> objlst = [Select Id from Sales__c where Id IN : idList WITH SECURITY_ENFORCED];
            if(Schema.sObjectType.Sales__c.isDeletable()){
                delete objlst;
            }
           
        }
        if(objectApiName == 'RWD_CX__Station__c'){
            if(Schema.sObjectType.Station__c.isDeletable()){
                List<Station__c> objlst = [Select Id from Station__c where Id IN : idList WITH SECURITY_ENFORCED];
                delete objlst;
            }
        }
        if(objectApiName == 'User'){
            if(Schema.sObjectType.User.isUpdateable()){
                // delete objlst;
                List<User> objlst = [Select Id,IsActive from User where Id IN : idList WITH SECURITY_ENFORCED];
                for(User us : objlst){
                    us.IsActive = false;
                }
                update objlst;
            }
        }
        if(objectApiName == 'RWD_CX__Claim__c'){
            if(Schema.sObjectType.Claim__c.isDeletable()){
                List<Claim__c> objlst = [Select Id from Claim__c where Id IN : idList WITH SECURITY_ENFORCED];
                delete objlst;
            }
        }
        if(objectApiName == 'RWD_CX__Customer__c' ){
            if(Schema.sObjectType.Customer__c.isDeletable()){
                List<Customer__c> objlst = [Select Id from Customer__c where Id IN : idList WITH SECURITY_ENFORCED];
                delete objlst;
            }
        }
        if(objectApiName == 'RWD_CX__Gift__c'){
            if(Schema.sObjectType.Gift__c.isDeletable()){
                List<Gift__c> objlst = [Select Id from Gift__c where Id IN : idList WITH SECURITY_ENFORCED];
                delete objlst;
            }
        }
        if(objectApiName == 'RWD_CX__Station_Gifts__c'){
            if(Schema.sObjectType.Station_Gifts__c.isDeletable()){
                List<Station_Gifts__c> objlst = [Select Id from Station_Gifts__c where Id IN : idList WITH SECURITY_ENFORCED];
                delete objlst;
            }
        }
        if(objectApiName == 'RWD_CX__Assign_Store__c'){
            if(Schema.sObjectType.Assign_Store__c.isDeletable()){
                List<Assign_Store__c> objlst = [Select Id from Assign_Store__c where Id IN : idList WITH SECURITY_ENFORCED];
                delete objlst;
            }
        }
         /*Database.DeleteResult[] deleteResults = Database.delete(idList, false);
            system.debug('isDeletablecheck objectApiName '+objectApiName);
            for (Database.DeleteResult result : deleteResults) {
                if (!result.isSuccess()) {
                    for (Database.Error err : result.getErrors()) {
                        System.debug('Error deleting record: ' + err.getMessage());
                    }
                }
            }*/
        
    }
    
   
    
}