force-app/main/default/objects/Assign_Store__c/Assign_Store__c.object-meta.xml
<CustomObject>
    <label>Assign Store</label>
    <nameField>
        <label>Assign Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assign Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_Store__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Assign Stores</relationshipLabel>
    <relationshipName>Assign_Stores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assign_Store__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assign_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Quantity_Claimed__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Claimed__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity Claimed</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Aadhaar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Number__c</fullName>
    <label>Aadhaar Number</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <label>Gift</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Gift ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Gift_Name__c.field-meta.xml
<CustomField>
    <fullName>Gift_Name__c</fullName>
    <label>Gift Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sales</label>
    <nameField>
        <displayFormat>SID-{00000}</displayFormat>
        <label>Sales ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Bill_Number__c.field-meta.xml
<CustomField>
    <fullName>Bill_Number__c</fullName>
    <label>Bill Number</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Employees__c.field-meta.xml
<CustomField>
    <fullName>Employees__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employees</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Station__c/Station__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/Station_Gifts__c.object-meta.xml
<CustomObject>
    <label>Store Gifts</label>
    <nameField>
        <displayFormat>SG-{000}</displayFormat>
        <label>Store Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipName>Station_Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Quantity_Added__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Added__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity Added</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Restock_Level__c.field-meta.xml
<CustomField>
    <fullName>Restock_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Restock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Store Gifts</relationshipLabel>
    <relationshipName>Station_Gifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar_Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>Employee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <label>Station</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/customerdataTest.cls
@isTest
public class customerdataTest {
    @isTest
    static void testGetCustomerInfo() 
    {
        // Create a test Customer__c record
        Customer__c testCustomer = new Customer__c(Phone__c = '9876543216');
        insert testCustomer;

        // Call the getCustomerInfo method
        Customer__c result = customerdata.getCustomerInfo('9876543216');

        // Assert that the result is not null and has the expected values
        System.assertNotEquals(null, result);
        System.assertEquals(testCustomer.Id, result.Id);
    }
    @isTest
    static void testGetCustomerInfo1() 
    {
        // Create a test Customer__c record
        Customer__c testCustomer = new Customer__c(Name__c='Test Customer',Aadhaar_Number__c='6534 9824 2573',Phone__c='9876543217');
        insert testCustomer;

        // Call the getCustomerInfo1 method
        Customer__c result = customerdata.getCustomerInfo1('9876543217');

        // Assert that the result is not null and has the expected values
        System.assertNotEquals(null, result);
        System.assertEquals(testCustomer.Id, result.Id);
        // Add more assertions for other fields if needed
    }
    
    @isTest
    static void testGetEmployeeInfo() {
        // Create a test Employee record
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
            // Create a test employee record
            user testEmployee = new user( ProfileId = profile.Id,
                Username = 'shruUsercc@example.com',
                Email = 'shcru@example.com',
                LastName = 'Process',
                Alias = 'trshcr',
                TimeZoneSidKey = 'America/New_York',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                                         phone='1234567890',
                Aadhar_Number__c='1234 5678 9012',Employee_Type__c='Sales');
            insert testEmployee;
    
        // Create a test Station record
        Station__c testStation = new Station__c(Name = 'Test Station');
        insert testStation;
            Assign_Store__c store= new Assign_Store__c();
            store.User__c=testEmployee.id;
            store.Store__c=testStation.id;
            insert store;
    
        // Create a test Customer record
        Customer__c testCustomer = new Customer__c(Name__c = 'Test Customer', Aadhaar_Number__c = '1764 5678 9012', Phone__c = '9876543215');
        insert testCustomer;
    
        // Create a test Sales record related to the Employee
        Sales__c testSales = new Sales__c(Employees__c = testEmployee.Id, Station__c = testStation.Id, Customer__c = testCustomer.Id, Amount__c = 100, Bill_Number__c = 'WRFSDSGD');
        insert testSales;
    
        // Start Test
        Test.startTest();
    
        // Call the method to test
        user emp = [SELECT Id, Aadhar_Number__c, Name,LastName,  Phone, Station__c,
                           (SELECT Id, Name, Station__r.Name, Customer__r.Name__c, Employees__r.Name, CreatedDate, 
                            Amount__c FROM Sales__r)
                           FROM user
                           where id=:testEmployee.Id];
            customerdata.getEmpolyeeInfo(emp.Phone);
    
        // End Test
        Test.stopTest();
    
        // Assert the result
        System.assertNotEquals(null, emp, 'Employee record should be retrieved');
        System.assertEquals('Process', emp.LastName, 'Employee Name should match');
        System.assertEquals('1234 5678 9012', emp.Aadhar_Number__c, 'Aadhar Number should match');
        System.assertEquals('1234567890', emp.Phone, 'Phone should match');
    
        // Verify related Sales records
        System.assertNotEquals(null, emp.Sales__r, 'Sales records should be queried');
        System.assertEquals(1, emp.Sales__r.size(), 'There should be one related Sales record');
        Sales__c relatedSales = emp.Sales__r[0];
        System.assertEquals(100, relatedSales.Amount__c, 'Amount should match');
    }
    
    @isTest
    static void testGetGiftsList() {
         Station__c testStation = new Station__c(Name = 'Test Station');
        insert testStation;
        // Create a test Employee__c record
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
       user testEmployee = new user( ProfileId = profile.Id,
            Username = 'shruUsercc@example.com',
            Email = 'shcru@example.com',
            LastName = 'Test Employee',
            Alias = 'trshcr',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
                                     phone='1234567890',
            Aadhar_Number__c='1234 5678 9012',Employee_Type__c='Sales');
        insert testEmployee;
        Assign_Store__c store= new Assign_Store__c();
        store.User__c=testEmployee.id;
        store.Store__c=testStation.id;
        insert store;
        Gift__c gf=new Gift__c();
        gf.Gift_Name__c='bottle';
        gf.Points__c=10;
        insert gf;
        
        Station_Gifts__c gifts = new Station_Gifts__c();
        gifts.Gift__c=gf.Id;
        gifts.Quantity_Added__c=100;
        gifts.Station__c=testStation.Id;
        gifts.Restock_Level__c=10;
        insert gifts;

        // Call the getGiftsList method
        List<Gift__c> result = customerdata.getGiftsList(testEmployee.Id);

        // Assert that the result is not null and has the expected values
        System.assertNotEquals(null, result);
    }
    
     @isTest
    static void testInsertClaim() {
        Station__c testStation = new Station__c(Name = 'Test Station');
        insert testStation;
        // Create a test Employee__c record
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        user testEmployee = new user( ProfileId = profile.Id,
            Username = 'shruUsercc@example.com',
            Email = 'shcru@example.com',
            LastName = 'Test Employee',
            Alias = 'trshcr',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            Station__c=testStation.Id,
            phone='1234567890',
            Aadhar_Number__c='1234 5678 9012',Employee_Type__c='Sales');
        insert testEmployee;
        Assign_Store__c store= new Assign_Store__c();
        store.User__c=testEmployee.id;
        store.Store__c=testStation.id;
        insert store;

        // Create a test Customer__c record
        Customer__c testCustomer = new Customer__c(Name__c = 'Test Customer',Phone__c='9876543244');
        insert testCustomer;

        // Create a test Gift__c record
        Gift__c testGift = new Gift__c(Gift_Name__c = 'Test Gift');
        insert testGift;
        Station_Gifts__c testStationGift = new Station_Gifts__c(Quantity_Added__c = 10, Gift__c = testGift.Id,Station__c = testStation.Id);
        insert testStationGift;
        // Call the insertClaim method
        Test.startTest();
        customerdata.insertClaim(testCustomer.Id, testGift.Id, testEmployee.Id,10);
        List<Claim__c> claims = [SELECT Id, Customer__c, Gift__c, Quantity_Claimed__c
                             FROM Claim__c 
                             WHERE Customer__c = :testCustomer.Id 
                             AND Gift__c = :testGift.Id AND Quantity_Claimed__c = 10];
        System.assertEquals(1, claims.size(), 'There should be exactly one Claim__c record.');
        Test.stopTest();
	}
    
  @isTest
    static void testFetchGiftNames() {
        // Create a test Station
        Station__c testStation = new Station__c(Name = 'Test Station');
        insert testStation;

        // Create a test Employee
       Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        user testEmployee = new user( ProfileId = profile.Id,
            Username = 'shruUsercc@example.com',
            Email = 'shcru@example.com',
            LastName = 'Test Employee',
            Alias = 'trshcr',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
                                     Station__c=testStation.Id,
                                     phone='1234567890',
            Aadhar_Number__c='1234 5678 9012',Employee_Type__c='Sales');
        insert testEmployee;
		Assign_Store__c store= new Assign_Store__c();
        store.User__c=testEmployee.id;
        store.Store__c=testStation.id;
        insert store;
        // Create some test Gifts with Station_Gifts records
        Gift__c gift1 = new Gift__c(Gift_Name__c = 'Gift 1');
        insert gift1;

        Station_Gifts__c stationGift1 = new Station_Gifts__c(Gift__c = gift1.Id, Station__c = testStation.Id);
        insert stationGift1;

        Gift__c gift2 = new Gift__c(Gift_Name__c = 'Gift 2');
        insert gift2;

        Station_Gifts__c stationGift2 = new Station_Gifts__c(Gift__c = gift2.Id, Station__c = testStation.Id);
        insert stationGift2;

        // Call the fetchGiftNames method
        Test.startTest();
        List<Gift__c> result = customerdata.fetchGiftNames(testEmployee.Id);
        Test.stopTest();

        // Assert that the expected gifts are in the result
        System.assertEquals(2, result.size(), 'Two gifts should be returned');
        System.assertEquals('Gift 1', result[0].Gift_Name__c, 'First gift name should match');
        System.assertEquals('Gift 2', result[1].Gift_Name__c, 'Second gift name should match');
    }
    
    @isTest
    static void testUpdateGift() {
        // Create a test Station
        Station__c testStation = new Station__c(Name = 'Test Station');
        insert testStation;

        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        user testEmployee = new user( ProfileId = profile.Id,
            Username = 'shruUsercc@example.com',
            Email = 'shcru@example.com',
            LastName = 'Test Employee',
            Alias = 'trshcr',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
                                     phone='1234567890',
                                Station__c=testStation.Id,     
            Aadhar_Number__c='1234 5678 9012',Employee_Type__c='Sales');
        insert testEmployee;
           Assign_Store__c store= new Assign_Store__c();
        store.User__c=testEmployee.id;
        store.Store__c=testStation.id;
        insert store;
        // Create a test Gift
        Gift__c testGift = new Gift__c(Gift_Name__c = 'Test Gift');
        insert testGift;

        // Create a Station_Gifts record
        Station_Gifts__c testStationGift = new Station_Gifts__c(Quantity_Added__c = 10, Gift__c = testGift.Id,Station__c = testStation.Id);
        insert testStationGift;

        // Call the updateGift method
        Test.startTest();
        customerdata.updateGift(testGift.Id, 5, testEmployee.Id);
        Test.stopTest();

        // Query the updated Station_Gifts record
        Station_Gifts__c updatedStationGift = [SELECT Quantity_Added__c FROM Station_Gifts__c WHERE Id = :testStationGift.Id];

        // Assert that the quantity has been updated
        System.assertEquals(15, updatedStationGift.Quantity_Added__c, 'Gift quantity should be updated');
    }
}