force-app/main/default/objects/Assign_Store__c/Assign_Store__c.object-meta.xml
<CustomObject>
    <label>Assign Store</label>
    <nameField>
        <label>Assign Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assign Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_Store__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Assign Stores</relationshipLabel>
    <relationshipName>Assign_Stores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assign_Store__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assign_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Quantity_Claimed__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Claimed__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity Claimed</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Aadhaar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Number__c</fullName>
    <label>Aadhaar Number</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Total_Loyality_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Loyality_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loyality Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <label>Gift</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Gift ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Gift_Name__c.field-meta.xml
<CustomField>
    <fullName>Gift_Name__c</fullName>
    <label>Gift Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sales</label>
    <nameField>
        <displayFormat>SID-{00000}</displayFormat>
        <label>Sales ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Bill_Number__c.field-meta.xml
<CustomField>
    <fullName>Bill_Number__c</fullName>
    <label>Bill Number</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Employees__c.field-meta.xml
<CustomField>
    <fullName>Employees__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employees</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Station__c/Station__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/Station_Gifts__c.object-meta.xml
<CustomObject>
    <label>Store Gifts</label>
    <nameField>
        <displayFormat>SG-{000}</displayFormat>
        <label>Store Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipName>Station_Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Quantity_Added__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Added__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity Added</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Restock_Level__c.field-meta.xml
<CustomField>
    <fullName>Restock_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Restock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Store Gifts</relationshipLabel>
    <relationshipName>Station_Gifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar_Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>Employee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <label>Station</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/genericDataTableControllerTest.cls
@isTest
public class genericDataTableControllerTest
{
    @isTest
    static void testGetRecords() {
        // Create test data and insert SObjects (replace with your object and fields)
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        // Call the getRecords method
        List<SObject> records = genericDataTableController.getRecords('Account', new List<String>{'Name'});
        
        // Assert that the records were retrieved
        System.assertEquals(1, records.size());
        System.assertEquals(testAccount.Id, records[0].get('Id'));
        System.assertEquals(testAccount.Name, records[0].get('Name'));
        
        // Clean up test data
        delete testAccount;
    }

    @isTest
    static void testGetRecords1() {
        // Test getRecords1 method for 'employee' branch
       Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        // Create a test employee record
        user testEmployee = new user( ProfileId = profile.Id,
            Username = 'shruUsercc@example.com',
            Email = 'shcru@example.com',
            LastName = 'shcru',
            Alias = 'trshcr',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            Aadhar_Number__c='6554 5566 8545',Employee_Type__c='Sales');
        insert testEmployee;
        List<SObject> recordsEmployee = genericDataTableController.getRecords1('employee', testEmployee.Id,'');
        System.assertNotEquals(null, recordsEmployee);
        
        // Test getRecords1 method for 'customer' branch
        Customer__c testCustomer = new Customer__c(Name__c = 'Test Customer',Aadhaar_Number__c='5643 6423 4588',Phone__c = '9876543266');
        insert testCustomer;
        List<SObject> recordsCustomer = genericDataTableController.getRecords1('customer', testCustomer.Id,'');
        System.assertNotEquals(null, recordsCustomer);
    }
    
      @isTest
    static void testGetRecords2() {
        // Test getRecords1 method for 'employee' branch
       Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        // Create a test employee record
        user testEmployee = new user( ProfileId = profile.Id,
            Username = 'shruUsercc@example.com',
            Email = 'shcru@example.com',
            LastName = 'shcru',
            Alias = 'trshcr',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            Aadhar_Number__c='6554 5566 8545',Employee_Type__c='Sales');
        insert testEmployee;
        Station__c testStation = new Station__c(Name = 'Test Station');
    insert testStation;
        Assign_Store__c store= new Assign_Store__c();
        store.User__c=testEmployee.id;
        store.Store__c=testStation.id;
        insert store;
         Customer__c testCustomer = new Customer__c(Name__c = 'Test Customer',Aadhaar_Number__c='5643 6423 4588',Phone__c = '9876543266');
        insert testCustomer;
        
        // Test getRecords1 method for 'customer' branch
       
            Sales__c testSales = new Sales__c(Employees__c = testEmployee.Id, Station__c = testStation.Id, Customer__c = testCustomer.Id, Amount__c = 100, Bill_Number__c = 'WRFSDSGD');
    insert testSales;
        List<SObject> recordsCustomer = genericDataTableController.getRecords1('empolyee', testEmployee.Id,'Sales__c');
        System.assertNotEquals(null, recordsCustomer);
    }

     @isTest
    static void testGetRecords3() {
        // Test getRecords1 method for 'employee' branch
       Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        // Create a test employee record
        user testEmployee = new user( ProfileId = profile.Id,
            Username = 'shruUsercc@example.com',
            Email = 'shcru@example.com',
            LastName = 'shcru',
            Alias = 'trshcr',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            Aadhar_Number__c='6554 5566 8545',Employee_Type__c='Sales');
        insert testEmployee;
        Station__c testStation = new Station__c(Name = 'Test Station');
    insert testStation;
        Assign_Store__c store= new Assign_Store__c();
        store.User__c=testEmployee.id;
        store.Store__c=testStation.id;
        insert store;
         Customer__c testCustomer = new Customer__c(Name__c = 'Test Customer',Aadhaar_Number__c='5643 6423 4588',Phone__c = '9876543266',Total_Loyality_Points__c=100);
        insert testCustomer;
        
        // Test getRecords1 method for 'customer' branch
       
            Sales__c testSales = new Sales__c(Employees__c = testEmployee.Id, Station__c = testStation.Id, Customer__c = testCustomer.Id, Amount__c = 100, Bill_Number__c = 'WRFSDSGD');
    insert testSales;
         Gift__c gf=new Gift__c();
        gf.Gift_Name__c='bottle';
        gf.Points__c=10;
        insert gf;
        
        Station_Gifts__c gifts = new Station_Gifts__c();
        gifts.Gift__c=gf.Id;
        gifts.Quantity_Added__c=100;
        gifts.Station__c=testStation.Id;
        gifts.Restock_Level__c=10;
        insert gifts;
        Claim__c claim=new Claim__c();
        claim.Station__c=testStation.Id;
        claim.Quantity_Claimed__c=2;
        claim.Gift__c=gf.Id;
        claim.Customer__c=testCustomer.Id;
         List<SObject> recordsCustomer = genericDataTableController.getRecords1('customer', testCustomer.Id,'Claim__c');
        System.assertEquals(1, recordsCustomer.size());
    }  
    @isTest
    static void testSearchDate() {
        // Test searchDate method
        Date startDate = Date.today().addDays(-5);
        Date endDate = Date.today();
        List<Sales__c> salesList = genericDataTableController.searchDate(startDate, endDate);
        System.assertNotEquals(null, salesList);
    }

    @isTest
    static void testDeleteSelectedRecords() {
        // Create a test record to delete
        Customer__c testSales = new Customer__c(Name__c='Test Customer',Aadhaar_Number__c='5643 6423 4588',Phone__c = '9876549916');
        insert testSales;
        
        // Test deleteSelectedRecords method
        List<Id> idList = new List<Id>{testSales.Id};
        Test.startTest();
        genericDataTableController.deleteSelectedRecords(idList);
        Test.stopTest();
        
        // Verify that the record has been deleted
        List<Customer__c> salesList = [SELECT Id FROM Customer__c WHERE Id = :testSales.Id];
        System.assertEquals(0, salesList.size());
    }
     @isTest
    static void testDeleteemptyRecords() {
        
        // Test deleteSelectedRecords method
        List<Id> idList = new List<Id>();
        Test.startTest();
        genericDataTableController.deleteSelectedRecords(idList);
        Test.stopTest();
        
        // Verify that the record has been deleted
        List<Customer__c> salesList = [SELECT Id FROM Customer__c WHERE Id IN :idList];
        System.assertEquals(0, salesList.size());
    }

}