force-app/main/default/objects/Assign_Store__c/Assign_Store__c.object-meta.xml
<CustomObject>
    <label>Assign Store</label>
    <nameField>
        <label>Assign Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assign Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_Store__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Assign Stores</relationshipLabel>
    <relationshipName>Assign_Stores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assign_Store__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assign_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Aadhaar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Number__c</fullName>
    <label>Aadhaar Number</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Total_Loyality_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Loyality_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loyality Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Configuration__c/Pricing_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Pricing Configuration</label>
</CustomObject>

force-app/main/default/objects/Pricing_Configuration__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sales</label>
    <nameField>
        <displayFormat>SID-{00000}</displayFormat>
        <label>Sales ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Bill_Number__c.field-meta.xml
<CustomField>
    <fullName>Bill_Number__c</fullName>
    <label>Bill Number</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Employees__c.field-meta.xml
<CustomField>
    <fullName>Employees__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employees</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Station__c/Station__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/salescreation.cls
public with sharing class salescreation {
    
    
    @AuraEnabled
    public static void creation(id customerid,id empid,integer gasamount,string billnumber){
        List<Pricing_Configuration__c > rangeList =[SELECT Id,Amount__c,Points__c 
                                                    from Pricing_Configuration__c WITH SECURITY_ENFORCED
                                                    order By Amount__c desc Limit 10000 ];
        Decimal earnedPoints = 0;

        Id storeid = [select id,User__c,Store__c from Assign_Store__c where User__c=:empid and Store__c!=''].Store__c;
        if (Schema.sObjectType.Sales__c.isCreateable()) {
        Sales__c sale = new Sales__c();
        sale.Amount__c = gasamount;
        sale.Customer__c = customerid;
        sale.Station__c=storeid;
        sale.Employees__c = empid;
        sale.Bill_Number__c=billnumber;
        insert sale;
        }
        System.debug(rangeList+'rangeList');
        for(Pricing_Configuration__c pc :rangeList){
            if(pc.Amount__c > gasamount) {
                earnedPoints = pc.Points__c;
            } else {
                break;
            }
        }
         System.debug(earnedPoints+'earnedPoints');
        if (customerid != null && earnedPoints > 0) {
            if (Schema.sObjectType.Customer__c.isUpdateable()) {
                Customer__c custData = [Select Id,Name__c,Phone__c,Total_Loyality_Points__c,Aadhaar_Number__c from Customer__c where Id =: customerid WITH SECURITY_ENFORCED];
               if( custData.Total_Loyality_Points__c==null)
              {
                   custData.Total_Loyality_Points__c=0;
                  custData.Total_Loyality_Points__c += earnedPoints;
                  System.debug(custData.Total_Loyality_Points__c+'custData.Total_Loyality_Points__c');
              }else{
                custData.Total_Loyality_Points__c += earnedPoints;
                  System.debug(custData.Total_Loyality_Points__c+'custData.Total_Loyality_Points__c else');
              }
                update custData;
            }
        }

    }
    
    @AuraEnabled
    public static Decimal getDailyRates(Decimal amt){
        Pricing_Configuration__c pricing = [SELECT Name,Amount__c,Points__c,Id from Pricing_Configuration__c where Amount__c =: amt WITH SECURITY_ENFORCED];
        return pricing.Amount__c;
    }


}