force-app/main/default/objects/Assign_Store__c/Assign_Store__c.object-meta.xml
<CustomObject>
    <label>Assign Store</label>
    <nameField>
        <label>Assign Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assign Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_Store__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Assign Stores</relationshipLabel>
    <relationshipName>Assign_Stores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assign_Store__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assign_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Quantity_Claimed__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Claimed__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity Claimed</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Aadhaar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Number__c</fullName>
    <label>Aadhaar Number</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Total_Loyality_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Loyality_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loyality Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <label>Gift</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Gift ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Gift_Image__c.field-meta.xml
<CustomField>
    <fullName>Gift_Image__c</fullName>
    <formula>IMAGE( Gift_Image_Link__c , &quot; &quot; ,150,200)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gift Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Gift_Image_Link__c</fullName>
    <label>Gift Image Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Name__c.field-meta.xml
<CustomField>
    <fullName>Gift_Name__c</fullName>
    <label>Gift Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sales</label>
    <nameField>
        <displayFormat>SID-{00000}</displayFormat>
        <label>Sales ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Employees__c.field-meta.xml
<CustomField>
    <fullName>Employees__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employees</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Station__c/Station__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/Station_Gifts__c.object-meta.xml
<CustomObject>
    <label>Store Gifts</label>
    <nameField>
        <displayFormat>SG-{000}</displayFormat>
        <label>Store Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Station_Gifts__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipName>Station_Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Quantity_Added__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Added__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity Added</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Quantity_InStock__c.field-meta.xml
<CustomField>
    <fullName>Quantity_InStock__c</fullName>
    <formula>Quantity_Added__c  -  Quantity_Used__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity InStock</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Restock_Level__c.field-meta.xml
<CustomField>
    <fullName>Restock_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Restock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Station_Gifts__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Store Gifts</relationshipLabel>
    <relationshipName>Station_Gifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar_Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <label>Station</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/customerdata.cls
public with sharing class customerdata {
    //Get Customer__c Details
    //   public Boolean isCreateable{get;set;}
    @AuraEnabled
    public static Customer__c getCustomerInfo(string customerPhone) 
    {
        Customer__c Customer = [SELECT Id,Aadhaar_Number__c,Name,Name__c,Phone__c,Total_Loyality_Points__c
                             FROM Customer__c 
                             WHERE Id=:customerPhone  WITH SECURITY_ENFORCED];
        return Customer;  
    }
    @AuraEnabled
    public static Customer__c getCustomerInfo1(string phone) 
    {
        Customer__c Customer = [SELECT Id,Aadhaar_Number__c,Name,Name__c,Phone__c,Total_Loyality_Points__c,(select Id,Name,Station__r.Name,Customer__r.Name__c,Employees__r.Name,CreatedDate,Amount__c from Sales__r) 
                             FROM Customer__c 
                             WHERE Id=:phone WITH SECURITY_ENFORCED];
        return Customer;  
    }
     @AuraEnabled
    public static user getEmpolyeeInfo(string empid) 
    {
        user emp = [SELECT Id,Name,Phone,Station__c,LastName,Aadhar_Number__c,(select Id,Name,Station__r.Name,Customer__r.Name__c,Employees__r.Name,CreatedDate,Amount__c from Sales__r) 
                             FROM user 
                             WHERE Id =:empid WITH SECURITY_ENFORCED];
        return emp;  
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Gift__c> getGiftsList(Id empid) 
    {
        user emp=[SELECT Id,Name,Station__c FROM user WHERE Id=:empid];
        id storeid=[select id,User__c,Store__c from Assign_Store__c where User__c=:empid and Store__c!=''].Store__c;
        list<Station_Gifts__c> stationGifts=[select id,name,Quantity_InStock__c, Gift__c,Station__c 
                                             from Station_Gifts__C where Quantity_InStock__c >=1 AND Station__c =:storeid WITH SECURITY_ENFORCED];
        list<id> giftsids=new list<id>();
        for(Station_Gifts__c gifts:stationGifts){
            giftsids.add(gifts.Gift__c);
        }
        return [SELECT Id, Name, Gift_Name__c,Points__c,Gift_Image__c,Gift_Image_Link__c
                FROM Gift__c where id In : giftsids WITH SECURITY_ENFORCED order by RWD_CX__Points__c Asc];
    }
    
    //Claim Record Creation    
    @AuraEnabled
    public static void insertClaim(id CustomerName, id GiftName, id empid,Integer quantity) 
    {
        user emp= [select Station__c from user where id=:empid];
         id storeid=[select id,User__c,Store__c from Assign_Store__c where User__c=:empid and Store__c!=''].Store__c;
       if (Schema.sObjectType.Claim__c.isCreateable()) {
            Claim__c claim=new Claim__c();
            claim.Customer__c=CustomerName;
            claim.Gift__c=GiftName;
            claim.Station__c=storeid;
            claim.Quantity_Claimed__c=quantity;
            insert claim;
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Station_Gifts__c> fetchGiftNames(Id empid) {
        List<Station_Gifts__c> giftNames = new List<Station_Gifts__c>();
        
        user emp=[SELECT Id,Name,Station__c FROM user WHERE Id=:empid];
        id storeid=[select id,User__c,Store__c from Assign_Store__c where User__c=:empid and Store__c!=''].Store__c;
          system.debug(storeid+'storeid');
        List<Station_Gifts__c> sgift = [SELECT Id,Name,Gift__r.Gift_Name__c,Quantity_InStock__c,Restock_Level__c FROM Station_Gifts__c where Station__c=:storeid WITH SECURITY_ENFORCED];
        system.debug(sgift+'sgift');
        for(Station_Gifts__c gifts:sgift){
                giftNames.add(gifts);
            
        }
        system.debug(giftNames+'giftNames');
        return giftNames;
    }
    
    //Update Gift Record When it Reaches to Restock Level    
    @AuraEnabled
    public static void updateGift(id GiftId,integer qty,id empid) 
    {
        user emp=[SELECT Id,Name,Station__c FROM user WHERE Id=:empid];
        id storeid=[select id,User__c,Store__c from Assign_Store__c where User__c=:empid and Store__c!=''].Store__c;
        if (Schema.sObjectType.Station_Gifts__c.isUpdateable()) {
            Station_Gifts__c gift=[select id,name,Quantity_Added__c, Gift__c,Station__c 
                                   from Station_Gifts__C where Gift__c=:GiftId   AND Station__c =:storeid WITH SECURITY_ENFORCED];
            
            gift.Quantity_Added__c+=qty;
            update gift;
        }
    }
    
    @AuraEnabled
    public static Integer getClaimRecordCount(String customerId) 
    {
		Integer count = 0;
        List<RWD_CX__Customer__c> lst =[SELECT Id,RWD_CX__Aadhaar_Number__c,Name,RWD_CX__Name__c,RWD_CX__Phone__c,RWD_CX__Total_Loyality_Points__c,(Select Id from RWD_CX__Claim__r) FROM RWD_CX__Customer__c where Id =:customerId];
        for(RWD_CX__Customer__c ls :lst){
            count = ls.RWD_CX__Claim__r.size();
        }
       
        return count;
    }
    
}