force-app/main/default/objects/Assign_Store__c/Assign_Store__c.object-meta.xml
<CustomObject>
    <label>Assign Store</label>
    <nameField>
        <label>Assign Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assign Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_Store__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Assign Stores</relationshipLabel>
    <relationshipName>Assign_Stores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assign_Store__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assign_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Aadhaar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Number__c</fullName>
    <label>Aadhaar Number</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Total_Loyality_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Loyality_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Loyality Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Configuration__c/Pricing_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Pricing Configuration</label>
</CustomObject>

force-app/main/default/objects/Pricing_Configuration__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sales</label>
    <nameField>
        <displayFormat>SID-{00000}</displayFormat>
        <label>Sales ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Employees__c.field-meta.xml
<CustomField>
    <fullName>Employees__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employees</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Station__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Station__c/Station__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar_Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>Employee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Station__c.field-meta.xml
<CustomField>
    <fullName>Station__c</fullName>
    <label>Station</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/salescreationTest.cls
@isTest
public class salescreationTest
{
   
    @isTest
    static void testCreation() {
        // Create a test Station record
        Station__c testStation = new Station__c(Name = 'Test Station');
        insert testStation;
        
        // Create a test Gas Rate record
        Pricing_Configuration__c price=new Pricing_Configuration__c();
        price.Name='110-220';
        price.Points__c=10;
        price.Amount__c=100;
        insert price;
        
         Pricing_Configuration__c price1=new Pricing_Configuration__c();
        price1.Name='110-220';
        price1.Points__c=10;
        price1.Amount__c=25;
        insert price1;
        // Create a test Employee record
          Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        // Create a test employee record
        user testEmployee = new user( ProfileId = profile.Id,
            Username = 'shruUsercc@example.com',
            Email = 'shcru@example.com',
            LastName = 'shcru',
            Alias = 'trshcr',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            Aadhar_Number__c='6554 5566 8545',Employee_Type__c='Sales');
        insert testEmployee;
        Assign_Store__c store= new Assign_Store__c();
        store.User__c=testEmployee.id;
        store.Store__c=testStation.id;
        insert store;

        // Create a test Customer record
        Customer__c testCustomer = new Customer__c(Name__c = 'Test Customer', Total_Loyality_Points__c=0,Aadhaar_Number__c = '6574 5566 8545',Phone__c='9123067888');
        insert testCustomer;


        // Call the method to test
        // You need to ensure that the SalesCreation class is accessible and exists
        // and that it defines the creation method with the correct signature.
        SalesCreation.creation(testCustomer.Id, testEmployee.Id, 50, 'ADSDS');

        // Query for the Sales__c record that should have been inserted
        Sales__c insertedSale = [SELECT Amount__c, Customer__c, Employees__c,  Station__c FROM Sales__c LIMIT 1];

        // Assert the inserted Sale__c record
        System.assertEquals(50, insertedSale.Amount__c, 'The Amount should be 50');
        System.assertEquals(testCustomer.Id, insertedSale.Customer__c, 'The Customer should match the testCustomer Id');
        System.assertEquals(testEmployee.Id, insertedSale.Employees__c, 'The Employee should match the testEmployee Id');
        System.assertEquals(testStation.Id, insertedSale.Station__c, 'The Station should match the testStation Id');
    }
    
    
    @isTest
    static void GetDailyRates()
    {
       Pricing_Configuration__c price=new Pricing_Configuration__c();
        price.Name='110-220';
        price.Points__c=10;
        price.Amount__c=20;
        insert price;
        
         decimal result = salescreation.getDailyRates(20);

        // Assert that the method returns the expected value
        System.assertEquals(20, result);
    }

}