force-app/main/default/objects/Station__c/Station__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Station__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Warangal</fullName>
            </value>
            <value>
                <fullName>Medak</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Gadwal</fullName>
            </value>
            <value>
                <fullName>RangaReddy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckSameCityAndStreetHandler.cls
public with sharing class CheckSameCityAndStreetHandler {
    public static void handleBeforeInsert(List<Station__c> newStation) {
        Set<String> uniqueCityStreetSet = new Set<String>();

        for (Station__c existingStation : [SELECT City__c, Street__c FROM Station__c WHERE City__c != null AND Street__c != null WITH SECURITY_ENFORCED]) {
            String cityStreet = existingStation.City__c + existingStation.Street__c;
            uniqueCityStreetSet.add(cityStreet);
        }

        for (Station__c Station : newStation) {
            String cityStreet = Station.City__c + Station.Street__c;
            if (uniqueCityStreetSet.contains(cityStreet)) {
                Station.addError('Records with the same City and Street are not allowed.');
            }
        }
    }
}